### ISSUE TITLE
Working properly in local

### ISSUE THREAD

**Issue by chozeur** [Coni63/codingame-readme-stats#9]
Hi,
When accessing the given api endpoint, only 'magic' does respond. 
Runing localy, eveything seems to be working as expected.
Btw thanks for this project that i've been looking for for a long time!

**Comment by Coni63** [comment]
Hello,

I'm glad you liked it :)

Sorry about this issue, I realized after the first deployment that only premium account on pythonanywhere can call external APIs and I've only taken a free-tier for now.

I'll probably share it on CG's discord one day or another. If there is a good feeling. I'll probably take a premium account (and increase the number of calls per seconds as well :D)

If you know another host for flask applications, suggestions are more than welcome ;)

**Comment by chozeur** [comment]
I've been trying to dockerize your app to potentialy host it myself. Feel free to reach me on discord: chozeur#0001

**Comment by Coni63** [comment]
The deployment is currently working on pythonanywhere with internet access. It may be moved to vercel once the deployment issue is fixed on vercel's side.
